w3c/wot-cg

Presentations/2022/Readme.md

Add how to build a community presentation links

---

Minutes/2022/2022_12_15-minutes.md

Here are the minutes from Netzo Meetup of 15.12. @miguelrk or @arturork could you have a look if everything is ok?

Add Netzo Meetup Minutes

---

README.md

plus a minor fix to the stackoverflow badge

Adding discord badge

---

Meetings/TPAC2023/README.md

We can incorporate the feedbacks of https://github.com/w3c/wot-cg/discussions/47 to this document.

TPAC2023 planning document

---

Meetings/TPAC2023/GroupUpdate/README.md

Creating the folder to host the introduction video and group update presentation

Group Updates Folder

---

Meetings/TPAC2023/GroupUpdate/WoT-TPAC.txt
Meetings/TPAC2023/GroupUpdate/WoT-TPAC.vtt

WoT Introduction video and text for TPAC
The video preview link is available below. It will be constantly updated:
https://murf.ai/share/llm4y2m8

Add TPAC video

---

Meetings/TPAC2023/GroupUpdate/WoT-TPAC.txt
Meetings/TPAC2023/GroupUpdate/WoT-TPAC.vtt

I forgot to sync before merging the previous PR

Sync TPAC Video with murf content

---

Tutorials/whatiswot/6-JSON_Schema_in_Practice/README.md

Storyline of 6th video

---

Tutorials/whatiswot/Project_Details/plan.md

Creating a plan.md document that documents the current state of the work (a precursor of the github project

Add What is WoT? Tutorial Plan

---

Meetings/TPAC2023/README.md

This documents the Agents CG and WoT WG joint sessions we have in TPAC 2023.

TPAC Joint Sessions

---

Tutorials/whatiswot/9-OSI_Layers/README.md

Storyline for 9th Video

---

Tutorials/whatiswot/10-Application_Domains/README.md

Storyline for 10th video

---

Tutorials/whatiswot/12-Building_Blocks/README.md

Storyline for 12th Video

---

Tutorials/whatiswot/11-Architecture_Patterns/README.md

Storyline for 11th video

---

.gitignore
Meetings/TPAC2023/README.md
Tutorials/quickstart/Readme.md
Tutorials/quickstart/index.js
Tutorials/quickstart/package-lock.json
Tutorials/quickstart/package.json

This is the hands-on tutorial for TPAC 2023. It is a simple consumer application task where a simple script is given to bootstrap everything. The following are still needed before merging:

Quickstart Tutorial

---

Meetings/TPAC2023/README.md

This updates:
- the joint sessions with WoT WG/IG. After merging, I will update the calendar entries.
- slide links

TPAC Readme Updates

---

Tutorials/quickstart/Readme.md

Note: I think on the long run we should remove the GDrive link.
I think it is getting out of sync very easily...

Change GDrive to a dynamic folder zip generator

---

README.md

One annoying thing is that the YouTube logo has pointy corners but others do not. I did not find a solution in the documentation.

Add YouTube logo and align height

---

Minutes/2023/2023_09_15-minutes.md

Given WG/IG was also present, they should review these minutes as well.

Add tpac minutes of second session

---

Minutes/2023/2023_09_14-minutes.md

The minutes will left for review for 1 week to allow edits. This was not a real cg session with discussion but there are still comments from participants.

TPAC Session 1 Minutes

---

CONTRIBUTING.md

This documents how we review meeting minutes to make everything more transparent

Add minute review process

---

Minutes/2023/2023_08_07-minutes.md

Not done yet, I need to copy over the rest from transcript and clean. Definitely not recommending to use a transcription tool instead of scribing. Even this took me almost an hour for an hour meeting. There are so many mistakes and technical terms like WoT, JSON are not transcribed correctly. We should either scribe during the meeting or record a video. Given the video is more annoying to edit and consume, we should keep on scribing.

07 August Internal Meeting Minutes

---

Minutes/2023/2023_10_02-minutes.md

@JKRhb @relu91 @joshco @lu-zero and Carl Mattocks (I could not find your GitHub handle) feel free to provide feedback and corrections

Add Internal Meeting Minutes of 02 October 2023

---

Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.txt
Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-JSON-Schema-3.vtt

- Please use the following for reviews: https://murf.ai/share/lmxpv0ix
- txt and vtt files added
- links have been removed in voiceover due to sounding long and unnatural, however now they are not part of the subtitle.

8th tutorial video review 

---

Tutorials/whatiswot/website/docs/intro.md

The workflow should be fixed now and this PR is to test it.

Testing the new workflow

---

Tutorials/whatiswot/14-Interaction_Affordances/Gathered_Information_TD.md

All the notes that i gathered for the upcoming videos: Forms, Security Definitions, Links. It is not complete, howevere can be used as a starting point.

Add TD notes

---

Tutorials/whatiswot/9-OSI_Layers/9-OSI-Layers.txt
Tutorials/whatiswot/9-OSI_Layers/9-OSI-Layers.vtt

-You can use the following link for review: https://murf.ai/share/lo7ro6z8
-Minor typing mistake ("," forgotten) is fixed.

9th video feedback application

---

.github/workflows/whatiswot-deploy.yml
.gitignore
Tutorials/whatiswot/README.md
Tutorials/whatiswot/website/README.md
Tutorials/whatiswot/website/docusaurus.config.js
Tutorials/whatiswot/website/package-lock.json
Tutorials/whatiswot/website/package.json
Tutorials/whatiswot/website/yarn.lock

This way both gh actions and netlify builds will look correct

Environment Variables for Tutorial Website

---

Tutorials/whatiswot/14-Interaction_Affordances/README.md

- Includes a table of contents for Video 14: Interaction Affordances

ToC and Script for Video 14: Interaction Affordances

---

Tutorials/whatiswot/15-Protocol_Level/README.md

- Includes a table of contents for Video 15: Protocol Level

ToC and Script for Video 15: Protocol Level

---

Tutorials/whatiswot/11-Applications in Smart Homes and Smart Cities/README.md

- I've changed the script according to recent feedback.

Changes to script of Video 11: Applications in Smart Homes and Smart Cities

---

Tutorials/whatiswot/12-Applications in Industrial and Agriculture Systems/README.md

- Updated the video script with the feedback from #195

Script and Presentation for Video 12: Applications in Industrial and Agriculture Systems

---

Tutorials/whatiswot/1-WoT/1-video-information.md
Tutorials/whatiswot/10-Building_Blocks/10-video-information.md
Tutorials/whatiswot/2-Payloads_and_Headers/2-video-information.md
Tutorials/whatiswot/3-JSON/3-video-information.md
Tutorials/whatiswot/4-JSON_in_Practice/4-video-information.md
Tutorials/whatiswot/5-JSON_Schema/5-video-information.md
Tutorials/whatiswot/6-JSON_Schema_in_Practice/6-video-information.md
Tutorials/whatiswot/7-JSON_Schema_in_Practice_2/7-video-information.md
Tutorials/whatiswot/8-JSON_Schema_in_Practice_3/8-video-information.md
Tutorials/whatiswot/9-OSI_Layers/9-video-information.md

We created a new playlist for the preliminary stuff. This takes it into account and also adds the new video information file for video 10.

Adapting video information files

---

Tutorials/whatiswot/website/docusaurus.config.js

This PR addresses issue #211 
Website footer has been reorganised and updated with more links

WoT Tutorial Website: Add more footer links

---

Tutorials/whatiswot/14-Interaction_Affordances/README.md

- Added a first draft that will serve as a base for the script of video 14

Tutorial 14 - Script: Interaction Affordances first draft
